sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAySTFdEDrxzUxyeM2d
    access-key-secret: kkkkkkkkkk
    bucket-name: xupiao-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx9381efb18c6f19b3
    secret: 59f7b24a71db6d683518c5868de52f58
